---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  name: cephblockpools.ceph.rook.io
spec:
  group: ceph.rook.io
  names:
    kind: CephBlockPool
    listKind: CephBlockPoolList
    plural: cephblockpools
    singular: cephblockpool
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: CephBlockPool represents a Ceph Storage Pool
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: PoolSpec represents the spec of ceph pool
            properties:
              compressionMode:
                default: none
                description: 'The inline compression mode in Bluestore OSD to set to (options are: none, passive, aggressive, force)'
                enum:
                - none
                - passive
                - aggressive
                - force
                type: string
              crushRoot:
                description: The root of the crush hierarchy utilized by the pool
                type: string
              deviceClass:
                description: 'The device class the OSD should set to (options are: hdd, ssd, or nvme)'
                enum:
                - ssd
                - hdd
                - nvme
                - ""
                type: string
              enableRBDStats:
                description: EnableRBDStats is used to enable gathering of statistics for all RBD images in the pool
                type: boolean
              erasureCoded:
                description: The erasure code settings
                properties:
                  algorithm:
                    description: The algorithm for erasure coding
                    type: string
                  codingChunks:
                    description: Number of coding chunks per object in an erasure coded storage pool (required for erasure-coded pool type)
                    maximum: 9
                    minimum: 0
                    type: integer
                  dataChunks:
                    description: Number of data chunks per object in an erasure coded storage pool (required for erasure-coded pool type)
                    maximum: 9
                    minimum: 0
                    type: integer
                required:
                - codingChunks
                - dataChunks
                type: object
              failureDomain:
                description: 'The failure domain: osd/host/(region or zone if available) - technically also any type in the crush map'
                type: string
              mirroring:
                description: The mirroring settings
                properties:
                  enabled:
                    description: Enabled whether this pool is mirrored or not
                    type: boolean
                  mode:
                    description: 'Mode is the mirroring mode: either pool or image'
                    type: string
                  snapshotSchedules:
                    description: SnapshotSchedules is the scheduling of snapshot for mirrored images/pools
                    items:
                      description: SnapshotScheduleSpec represents the snapshot scheduling settings of a mirrored pool
                      properties:
                        interval:
                          description: Interval represent the periodicity of the snapshot.
                          type: string
                        startTime:
                          description: StartTime indicates when to start the snapshot
                          type: string
                      type: object
                    type: array
                type: object
              parameters:
                additionalProperties:
                  type: string
                description: Parameters is a list of properties to enable on a given pool
                nullable: true
                type: object
                x-kubernetes-preserve-unknown-fields: true
              quotas:
                description: The quota settings
                nullable: true
                properties:
                  maxBytes:
                    description: MaxBytes represents the quota in bytes Deprecated in favor of MaxSize
                    format: int64
                    type: integer
                  maxObjects:
                    description: MaxObjects represents the quota in objects
                    format: int64
                    type: integer
                  maxSize:
                    description: MaxSize represents the quota in bytes as a string
                    pattern: ^[0-9]+[\.]?[0-9]*([KMGTPE]i|[kMGTPE])?$
                    type: string
                type: object
              replicated:
                description: The replication settings
                properties:
                  replicasPerFailureDomain:
                    description: ReplicasPerFailureDomain the number of replica in the specified failure domain
                    minimum: 1
                    type: integer
                  requireSafeReplicaSize:
                    description: RequireSafeReplicaSize if false allows you to set replica 1
                    type: boolean
                  size:
                    description: Size - Number of copies per object in a replicated storage pool, including the object itself (required for replicated pool type)
                    minimum: 1
                    type: integer
                  subFailureDomain:
                    description: SubFailureDomain the name of the sub-failure domain
                    type: string
                  targetSizeRatio:
                    description: TargetSizeRatio gives a hint (%) to Ceph in terms of expected consumption of the total cluster capacity
                    type: number
                required:
                - size
                type: object
              statusCheck:
                description: The mirroring statusCheck
                properties:
                  mirror:
                    description: HealthCheckSpec represents the health check of an object store bucket
                    nullable: true
                    properties:
                      disabled:
                        type: boolean
                      interval:
                        description: Interval is the internal in second or minute for the health check to run like 60s for 60 seconds
                        type: string
                      timeout:
                        type: string
                    type: object
                type: object
                x-kubernetes-preserve-unknown-fields: true
            type: object
          status:
            description: CephBlockPoolStatus represents the mirroring status of Ceph Storage Pool
            properties:
              info:
                additionalProperties:
                  type: string
                description: Use only info and put mirroringStatus in it?
                nullable: true
                type: object
              mirroringInfo:
                description: MirroringInfoSpec is the status of the pool mirroring
                properties:
                  details:
                    type: string
                  lastChanged:
                    type: string
                  lastChecked:
                    type: string
                  mode:
                    description: Mode is the mirroring mode
                    type: string
                  peers:
                    description: Peers are the list of peer sites connected to that cluster
                    items:
                      description: PeersSpec contains peer details
                      properties:
                        client_name:
                          description: ClientName is the CephX user used to connect to the peer
                          type: string
                        direction:
                          description: Direction is the peer mirroring direction
                          type: string
                        mirror_uuid:
                          description: MirrorUUID is the mirror UUID
                          type: string
                        site_name:
                          description: SiteName is the current site name
                          type: string
                        uuid:
                          description: UUID is the peer UUID
                          type: string
                      type: object
                    type: array
                  site_name:
                    description: SiteName is the current site name
                    type: string
                type: object
              mirroringStatus:
                description: MirroringStatusSpec is the status of the pool mirroring
                properties:
                  details:
                    description: Details contains potential status errors
                    type: string
                  lastChanged:
                    description: LastChanged is the last time time the status last changed
                    type: string
                  lastChecked:
                    description: LastChecked is the last time time the status was checked
                    type: string
                  summary:
                    description: Summary is the mirroring status summary
                    properties:
                      daemon_health:
                        description: DaemonHealth is the health of the mirroring daemon
                        type: string
                      health:
                        description: Health is the mirroring health
                        type: string
                      image_health:
                        description: ImageHealth is the health of the mirrored image
                        type: string
                      states:
                        description: States is the various state for all mirrored images
                        nullable: true
                        properties:
                          error:
                            description: Error is when the mirroring state is errored
                            type: integer
                          replaying:
                            description: Replaying is when the replay of the mirroring journal is on-going
                            type: integer
                          starting_replay:
                            description: StartingReplay is when the replay of the mirroring journal starts
                            type: integer
                          stopped:
                            description: Stopped is when the mirroring state is stopped
                            type: integer
                          stopping_replay:
                            description: StopReplaying is when the replay of the mirroring journal stops
                            type: integer
                          syncing:
                            description: Syncing is when the image is syncing
                            type: integer
                          unknown:
                            description: Unknown is when the mirroring state is unknown
                            type: integer
                        type: object
                    type: object
                type: object
              phase:
                description: ConditionType represent a resource's status
                type: string
              snapshotScheduleStatus:
                description: SnapshotScheduleStatusSpec is the status of the snapshot schedule
                properties:
                  details:
                    description: Details contains potential status errors
                    type: string
                  lastChanged:
                    description: LastChanged is the last time time the status last changed
                    type: string
                  lastChecked:
                    description: LastChecked is the last time time the status was checked
                    type: string
                  snapshotSchedules:
                    description: SnapshotSchedules is the list of snapshots scheduled
                    items:
                      description: SnapshotSchedulesSpec is the list of snapshot scheduled for images in a pool
                      properties:
                        image:
                          description: Image is the mirrored image
                          type: string
                        items:
                          description: Items is the list schedules times for a given snapshot
                          items:
                            description: SnapshotSchedule is a schedule
                            properties:
                              interval:
                                description: Interval is the interval in which snapshots will be taken
                                type: string
                              start_time:
                                description: StartTime is the snapshot starting time
                                type: string
                            type: object
                          type: array
                        namespace:
                          description: Namespace is the RADOS namespace the image is part of
                          type: string
                        pool:
                          description: Pool is the pool name
                          type: string
                      type: object
                    nullable: true
                    type: array
                type: object
            type: object
            x-kubernetes-preserve-unknown-fields: true
        required:
        - metadata
        - spec
        type: object
    served: true
    storage: true
