apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: odf-blackbox-scc-role
  labels:
    app.kubernetes.io/name: odf-blackbox-exporter
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - odf-blackbox-scc
  verbs:
  - use
