kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ocs-metrics-svc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ocs-metrics-svc
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring