
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: cephobjectzones.ceph.rook.io
spec:
  group: ceph.rook.io
  names:
    kind: CephObjectZone
    listKind: CephObjectZoneList
    plural: cephobjectzones
    singular: cephobjectzone
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: CephObjectZone represents a Ceph Object Store Gateway Zone
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ObjectZoneSpec represent the spec of an ObjectZone
            properties:
              dataPool:
                description: The data pool settings
                properties:
                  compressionMode:
                    default: none
                    description: 'The inline compression mode in Bluestore OSD to
                      set to (options are: none, passive, aggressive, force)'
                    enum:
                    - ""
                    - none
                    - passive
                    - aggressive
                    - force
                    type: string
                  crushRoot:
                    description: The root of the crush hierarchy utilized by the pool
                    type: string
                  deviceClass:
                    description: 'The device class the OSD should set to (options
                      are: hdd, ssd, or nvme)'
                    enum:
                    - ssd
                    - hdd
                    - nvme
                    - ""
                    type: string
                  enableRBDStats:
                    description: EnableRBDStats is used to enable gathering of statistics
                      for all RBD images in the pool
                    type: boolean
                  erasureCoded:
                    description: The erasure code settings
                    properties:
                      algorithm:
                        description: The algorithm for erasure coding
                        type: string
                      codingChunks:
                        description: Number of coding chunks per object in an erasure
                          coded storage pool (required for erasure-coded pool type)
                        maximum: 9
                        minimum: 0
                        type: integer
                      dataChunks:
                        description: Number of data chunks per object in an erasure
                          coded storage pool (required for erasure-coded pool type)
                        maximum: 9
                        minimum: 0
                        type: integer
                    required:
                    - codingChunks
                    - dataChunks
                    type: object
                  failureDomain:
                    description: 'The failure domain: osd/host/(region or zone if
                      available) - technically also any type in the crush map'
                    type: string
                  mirroring:
                    description: The mirroring settings
                    properties:
                      enabled:
                        description: Enabled whether this pool is mirrored or not
                        type: boolean
                      mode:
                        description: 'Mode is the mirroring mode: either pool or image'
                        type: string
                      snapshotSchedules:
                        description: SnapshotSchedules is the scheduling of snapshot
                          for mirrored images/pools
                        items:
                          description: SnapshotScheduleSpec represents the snapshot
                            scheduling settings of a mirrored pool
                          properties:
                            interval:
                              description: Interval represent the periodicity of the
                                snapshot.
                              type: string
                            startTime:
                              description: StartTime indicates when to start the snapshot
                              type: string
                          type: object
                        type: array
                    type: object
                  parameters:
                    additionalProperties:
                      type: string
                    description: Parameters is a list of properties to enable on a
                      given pool
                    nullable: true
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  quotas:
                    description: The quota settings
                    nullable: true
                    properties:
                      maxBytes:
                        description: MaxBytes represents the quota in bytes Deprecated
                          in favor of MaxSize
                        format: int64
                        type: integer
                      maxObjects:
                        description: MaxObjects represents the quota in objects
                        format: int64
                        type: integer
                      maxSize:
                        description: MaxSize represents the quota in bytes as a string
                        pattern: ^[0-9]+[\.]?[0-9]*([KMGTPE]i|[kMGTPE])?$
                        type: string
                    type: object
                  replicated:
                    description: The replication settings
                    properties:
                      replicasPerFailureDomain:
                        description: ReplicasPerFailureDomain the number of replica
                          in the specified failure domain
                        minimum: 1
                        type: integer
                      requireSafeReplicaSize:
                        description: RequireSafeReplicaSize if false allows you to
                          set replica 1
                        type: boolean
                      size:
                        description: Size - Number of copies per object in a replicated
                          storage pool, including the object itself (required for
                          replicated pool type)
                        minimum: 1
                        type: integer
                      subFailureDomain:
                        description: SubFailureDomain the name of the sub-failure
                          domain
                        type: string
                      targetSizeRatio:
                        description: TargetSizeRatio gives a hint (%) to Ceph in terms
                          of expected consumption of the total cluster capacity
                        type: number
                    required:
                    - size
                    type: object
                  statusCheck:
                    description: The mirroring statusCheck
                    properties:
                      mirror:
                        description: HealthCheckSpec represents the health check of
                          an object store bucket
                        nullable: true
                        properties:
                          disabled:
                            type: boolean
                          interval:
                            description: Interval is the internal in second or minute
                              for the health check to run like 60s for 60 seconds
                            type: string
                          timeout:
                            type: string
                        type: object
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                type: object
              metadataPool:
                description: The metadata pool settings
                properties:
                  compressionMode:
                    default: none
                    description: 'The inline compression mode in Bluestore OSD to
                      set to (options are: none, passive, aggressive, force)'
                    enum:
                    - ""
                    - none
                    - passive
                    - aggressive
                    - force
                    type: string
                  crushRoot:
                    description: The root of the crush hierarchy utilized by the pool
                    type: string
                  deviceClass:
                    description: 'The device class the OSD should set to (options
                      are: hdd, ssd, or nvme)'
                    enum:
                    - ssd
                    - hdd
                    - nvme
                    - ""
                    type: string
                  enableRBDStats:
                    description: EnableRBDStats is used to enable gathering of statistics
                      for all RBD images in the pool
                    type: boolean
                  erasureCoded:
                    description: The erasure code settings
                    properties:
                      algorithm:
                        description: The algorithm for erasure coding
                        type: string
                      codingChunks:
                        description: Number of coding chunks per object in an erasure
                          coded storage pool (required for erasure-coded pool type)
                        maximum: 9
                        minimum: 0
                        type: integer
                      dataChunks:
                        description: Number of data chunks per object in an erasure
                          coded storage pool (required for erasure-coded pool type)
                        maximum: 9
                        minimum: 0
                        type: integer
                    required:
                    - codingChunks
                    - dataChunks
                    type: object
                  failureDomain:
                    description: 'The failure domain: osd/host/(region or zone if
                      available) - technically also any type in the crush map'
                    type: string
                  mirroring:
                    description: The mirroring settings
                    properties:
                      enabled:
                        description: Enabled whether this pool is mirrored or not
                        type: boolean
                      mode:
                        description: 'Mode is the mirroring mode: either pool or image'
                        type: string
                      snapshotSchedules:
                        description: SnapshotSchedules is the scheduling of snapshot
                          for mirrored images/pools
                        items:
                          description: SnapshotScheduleSpec represents the snapshot
                            scheduling settings of a mirrored pool
                          properties:
                            interval:
                              description: Interval represent the periodicity of the
                                snapshot.
                              type: string
                            startTime:
                              description: StartTime indicates when to start the snapshot
                              type: string
                          type: object
                        type: array
                    type: object
                  parameters:
                    additionalProperties:
                      type: string
                    description: Parameters is a list of properties to enable on a
                      given pool
                    nullable: true
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  quotas:
                    description: The quota settings
                    nullable: true
                    properties:
                      maxBytes:
                        description: MaxBytes represents the quota in bytes Deprecated
                          in favor of MaxSize
                        format: int64
                        type: integer
                      maxObjects:
                        description: MaxObjects represents the quota in objects
                        format: int64
                        type: integer
                      maxSize:
                        description: MaxSize represents the quota in bytes as a string
                        pattern: ^[0-9]+[\.]?[0-9]*([KMGTPE]i|[kMGTPE])?$
                        type: string
                    type: object
                  replicated:
                    description: The replication settings
                    properties:
                      replicasPerFailureDomain:
                        description: ReplicasPerFailureDomain the number of replica
                          in the specified failure domain
                        minimum: 1
                        type: integer
                      requireSafeReplicaSize:
                        description: RequireSafeReplicaSize if false allows you to
                          set replica 1
                        type: boolean
                      size:
                        description: Size - Number of copies per object in a replicated
                          storage pool, including the object itself (required for
                          replicated pool type)
                        minimum: 1
                        type: integer
                      subFailureDomain:
                        description: SubFailureDomain the name of the sub-failure
                          domain
                        type: string
                      targetSizeRatio:
                        description: TargetSizeRatio gives a hint (%) to Ceph in terms
                          of expected consumption of the total cluster capacity
                        type: number
                    required:
                    - size
                    type: object
                  statusCheck:
                    description: The mirroring statusCheck
                    properties:
                      mirror:
                        description: HealthCheckSpec represents the health check of
                          an object store bucket
                        nullable: true
                        properties:
                          disabled:
                            type: boolean
                          interval:
                            description: Interval is the internal in second or minute
                              for the health check to run like 60s for 60 seconds
                            type: string
                          timeout:
                            type: string
                        type: object
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                type: object
              zoneGroup:
                description: The display name for the ceph users
                type: string
            required:
            - dataPool
            - metadataPool
            - zoneGroup
            type: object
          status:
            description: Status represents the status of an object
            properties:
              phase:
                type: string
            type: object
            x-kubernetes-preserve-unknown-fields: true
        required:
        - metadata
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
