---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.1
  name: storageconsumers.ocs.openshift.io
spec:
  group: ocs.openshift.io
  names:
    kind: StorageConsumer
    listKind: StorageConsumerList
    plural: storageconsumers
    singular: storageconsumer
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: StorageConsumer is the Schema for the storageconsumers API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: StorageConsumerSpec defines the desired state of StorageConsumer
            properties:
              enable:
                description: Enable flag ignores a reconcile if set to false
                type: boolean
              resourceNameMappingConfigMap:
                description: |-
                  LocalObjectReference contains enough information to let you locate the
                  referenced object inside the same namespace.
                properties:
                  name:
                    default: ""
                    description: |-
                      Name of the referent.
                      This field is effectively required, but due to backwards compatibility is
                      allowed to be empty. Instances of this type with an empty value here are
                      almost certainly wrong.
                      More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    type: string
                type: object
                x-kubernetes-map-type: atomic
              storageClasses:
                items:
                  properties:
                    name:
                      type: string
                  required:
                  - name
                  type: object
                type: array
              storageQuotaInGiB:
                description: StorageQuotaInGiB describes quota for the consumer
                type: integer
              volumeGroupSnapshotClasses:
                items:
                  properties:
                    name:
                      type: string
                  required:
                  - name
                  type: object
                type: array
              volumeReplicationClasses:
                items:
                  properties:
                    name:
                      type: string
                  required:
                  - name
                  type: object
                type: array
              volumeSnapshotClasses:
                items:
                  properties:
                    name:
                      type: string
                  required:
                  - name
                  type: object
                type: array
            type: object
          status:
            description: StorageConsumerStatus defines the observed state of StorageConsumer
            properties:
              cephResources:
                description: CephResources provide details of created ceph resources
                  required for external storage
                items:
                  description: CephResourcesSpec hold details of created ceph resources
                    required for external storage
                  properties:
                    cephClients:
                      additionalProperties:
                        type: string
                      description: CephClients holds the name of CephClients mapped
                        to the created ceph resource
                      type: object
                    kind:
                      description: Kind describes the kind of created ceph resource
                      type: string
                    name:
                      description: Name describes the name of created ceph resource
                      type: string
                    status:
                      description: Phase describes the phase of created ceph resource
                      type: string
                  type: object
                type: array
              client:
                description: Information of storage client received from consumer
                properties:
                  clientId:
                    description: ID is the k8s UID of connected storageclient
                    type: string
                  clusterId:
                    description: ClusterID is the id of the openshift cluster
                    type: string
                  clusterName:
                    description: ClusterName is the name of the openshift cluster
                    type: string
                  name:
                    description: Name is the name of connected storageclient
                    type: string
                  operatorNamespace:
                    description: Client Operator Namespace
                    type: string
                  operatorVersion:
                    description: StorageClient Operator Version
                    type: string
                  platformVersion:
                    description: StorageClient Platform Version
                    type: string
                  storageQuotaUtilizationRatio:
                    description: StorageQuotaUtilizationRatio is the ratio of utilized
                      quota of connected client
                    type: number
                type: object
              lastHeartbeat:
                description: Timestamp of last heartbeat received from consumer
                format: date-time
                type: string
              onboardingTicketSecret:
                description: |-
                  LocalObjectReference contains enough information to let you locate the
                  referenced object inside the same namespace.
                properties:
                  name:
                    default: ""
                    description: |-
                      Name of the referent.
                      This field is effectively required, but due to backwards compatibility is
                      allowed to be empty. Instances of this type with an empty value here are
                      almost certainly wrong.
                      More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    type: string
                type: object
                x-kubernetes-map-type: atomic
              resourceNameMappingConfigMap:
                description: |-
                  LocalObjectReference contains enough information to let you locate the
                  referenced object inside the same namespace.
                properties:
                  name:
                    default: ""
                    description: |-
                      Name of the referent.
                      This field is effectively required, but due to backwards compatibility is
                      allowed to be empty. Instances of this type with an empty value here are
                      almost certainly wrong.
                      More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    type: string
                type: object
                x-kubernetes-map-type: atomic
              state:
                description: State describes the state of StorageConsumer
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
