---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: storageclusterinitializations.ocs.openshift.io
spec:
  group: ocs.openshift.io
  names:
    kind: StorageClusterInitialization
    listKind: StorageClusterInitializationList
    plural: storageclusterinitializations
    singular: storageclusterinitialization
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            failureDomain:
              description: FailureDomain is the base CRUSH element Ceph will use to
                distribute its data replicas for the default CephBlockPool
              type: string
            resources:
              additionalProperties:
                type: object
              description: Resources is set by the StorageCluster controller when
                it creates the StorageClusterInitialization resource, and is set to
                the StorageCluster.Spec.Resources
              type: object
          type: object
        status:
          properties:
            cephBlockPoolsCreated:
              type: boolean
            cephFilesystemsCreated:
              type: boolean
            cephObjectStoreUsersCreated:
              type: boolean
            cephObjectStoresCreated:
              type: boolean
            conditions:
              description: Conditions describes the state of the StorageClusterInitialization
                resource.
              items:
                properties:
                  lastHeartbeatTime:
                    format: date-time
                    type: string
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                - lastHeartbeatTime
                - lastTransitionTime
                type: object
              type: array
            errorMessage:
              type: string
            phase:
              description: Phase describes the Phase of StorageClusterInitialization
                This is used by OLM UI to provide status information to the user
              type: string
            relatedObjects:
              description: RelatedObjects is a list of objects created and maintained
                by this operator. Object references will be added to this list after
                they have been created AND found in the cluster.
              items:
                type: object
              type: array
            storageClassesCreated:
              type: boolean
          type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
