---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  name: storageprofiles.ocs.openshift.io
spec:
  group: ocs.openshift.io
  names:
    kind: StorageProfile
    listKind: StorageProfileList
    plural: storageprofiles
    singular: storageprofile
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: StorageProfile is the Schema for the storageprofiles API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: StorageProfileSpec defines the desired state of StorageProfile
            properties:
              blockPoolConfiguration:
                description: configurations to use for  profile specific blockpool.
                properties:
                  parameters:
                    additionalProperties:
                      type: string
                    type: object
                type: object
                x-kubernetes-validations:
                - message: BlockPoolConfiguration is immutable
                  rule: self == oldSelf
              deviceClass:
                description: DeviceClass is the deviceclass name.
                maxLength: 512
                type: string
                x-kubernetes-validations:
                - message: DeviceClass is immutable
                  rule: self == oldSelf
              sharedFilesystemConfiguration:
                description: configurations to use for cephfilesystem.
                properties:
                  parameters:
                    additionalProperties:
                      type: string
                    type: object
                type: object
                x-kubernetes-validations:
                - message: SharedFilesystemConfiguration is immutable
                  rule: self == oldSelf
            type: object
            x-kubernetes-validations:
            - message: deviceClass is required once set
              rule: '!has(oldSelf.deviceClass) || has(self.deviceClass)'
            - message: sharedFilesystemConfiguration is required once set
              rule: '!has(oldSelf.sharedFilesystemConfiguration) || has(self.sharedFilesystemConfiguration)'
            - message: blockPoolConfiguration is required once set
              rule: '!has(oldSelf.blockPoolConfiguration) || has(self.blockPoolConfiguration)'
          status:
            description: StorageProfileStatus defines the observed state of StorageProfile
            properties:
              phase:
                description: Phase describes the Phase of StorageProfile This is used
                  by OLM UI to provide status information to the user
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
