---
name: ocs-operator sanity checks

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run shellcheck
        run: make shellcheck-test

  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.18", "1.19"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # TODO: Our code currently does not pass linting using Go 1.19, so
      # avoiding it until we bump go.mod to 1.19 as well.
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49.0

          # The weird NO_FUTURE thing is a workaround suggested here:
          # # https://github.com/golangci/golangci-lint-action/issues/119#issuecomment-981090648
          args: "--out-${NO_FUTURE}format=colored-line-number --timeout=6m ./..."

  go-test:
    name: go test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.18", "1.19"]
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run go test
        run: make unit-test

  verify-changes:
    name: verify generated changes
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        go: ["1.18", "1.19"]
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Verify go dependencies
        run: make verify-deps

      - name: Verify generated code and configs
        run: make verify-generated

      - name: Verify CSV changes
        run: make verify-latest-csv

      - name: Verify bundle changes
        run: make verify-operator-bundle

      - name: Verify deployment YAML
        run: make verify-latest-deploy-yaml

  code-spell:
    name: verify code spellings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: codespell-project/actions-codespell@master
        with:
          exclude_file: go.sum
          check_filenames: true
          check_hidden: true
          skip: vendor
          ignore_words_list: xdescribe,contails,shouldnot,NotIn,notin
